name: Build and Publish Python Wheels

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Extract version from package
        id: get_version
        run: |
          if [ ${{ matrix.os }} == "windows-latest" ]; then
            $VERSION = (python setup.py --version).strip()
            echo "VERSION=$VERSION" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          else
            VERSION=$(python setup.py --version)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: wheels

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wheels
          asset_name: wheels-${{ github.sha }}.zip
          asset_content_type: application/zip